# Generated by Django 4.2.5 on 2023-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featuredImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
